# Site settings
title:          ITS Design Studio
description:    "A storytellers for design"
url:            "https://itsdesignteam.github.io/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         ITS Design Studio
  url:          https://itsdesignteam.github.io/
  email:        itsteam.stios@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-admin
  - github-pages
  - jemoji
  - jekyll-include-cache

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock]