# Site settings
title:          Its Team
description:    "A storytellers for design"
url:            "https://www.itsteam.kr"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         ItsTeam
  url:          https://www.itsteam.kr
  email:        itsteam.stios@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages
theme:          stios-theme

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-admin
  - jemoji
  - jekyll-include-cache


# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]